# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=60)),
                ('use_case', models.TextField(blank=True, max_length=140)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department(Optional)')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization(Optional)')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title(Optional)')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country(Optional)')),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='About(Optional)')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
