# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_faqs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='questions',
            new_name='question',
        ),
    ]
