# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_currentmember_history_leader_oldmember_publication_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faqs',
            new_name='FAQ',
        ),
    ]
