# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_music'),
        ('app', '0009_auto_20170612_1719'),
    ]

    operations = [
    ]
