# Generated by Django 2.0.5 on 2018-05-29 03:46

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170725_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subteam',
            field=models.CharField(choices=[('I', 'Image team'), ('UI', 'Web UI team'), ('D+API', 'Database and API')], default='I', max_length=50, validators=[app.validators.validateName], verbose_name='Subteam'),
        ),
    ]
