# Generated by Django 2.0.6 on 2018-06-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170725_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subteam',
            field=models.CharField(blank=True, choices=[('I', 'Image Analysis'), ('UI', 'Web UI'), ('D+API', 'API team'), ('One B', 'One Billion Images Team'), ('Intel', 'Intel Target Tracking')], default='blank', max_length=50, verbose_name='Subteam'),
        ),
    ]
