# Generated by Django 2.0.5 on 2018-06-27 16:03

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_member_subteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collabname', models.CharField(max_length=100, verbose_name='Collaborator')),
                ('collabdescr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('collablink', models.CharField(blank=True, max_length=300, null=True, validators=[app.validators.validateURL], verbose_name='Link to Site')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='subteam',
            field=models.CharField(blank=True, choices=[('I', 'Image Analysis'), ('UI', 'Web UI'), ('D+API', 'API team'), ('One B', 'One Billion Images Team'), ('Intel', 'Embedded Computer Vision')], default='blank', max_length=50, verbose_name='Subteam'),
        ),
    ]
