# Generated by Django 2.0.5 on 2018-06-07 14:38

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_member_subteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subteam',
            field=models.CharField(choices=[('I', 'Image Analysis'), ('UI', 'Web UI'), ('D+API', 'API team'), ('One B', 'One Billion Images Team'), ('Intel', 'Intel Target Tracking')], default='I', max_length=50, validators=[app.validators.validateName], verbose_name='Subteam'),
        ),
    ]
