# Generated by Django 2.0.6 on 2018-07-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_location'),
        ('app', '0016_auto_20180627_1656'),
    ]

    operations = [
    ]
