# Generated by Django 2.0.5 on 2018-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20180703_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraID', models.CharField(max_length=100, verbose_name='Camera ID')),
            ],
        ),
    ]
