# Generated by Django 2.0.6 on 2018-07-05 14:28

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20180703_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponname', models.CharField(max_length=100, verbose_name='Sponsor')),
                ('spondescr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('sponlink', models.CharField(blank=True, max_length=300, null=True, validators=[app.validators.validateURL], verbose_name='Link to Site')),
            ],
        ),
    ]
