# Generated by Django 2.0.5 on 2018-07-05 02:15

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20180703_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posterimg', models.CharField(max_length=300, validators=[app.validators.validateURL], verbose_name='Poster Image')),
            ],
        ),
    ]
