# Generated by Django 2.0.5 on 2018-07-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_poster'),
        ('app', '0019_sponsor'),
    ]

    operations = [
    ]
