# Generated by Django 2.0.5 on 2018-07-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_reportedcamera'),
        ('app', '0019_sponsor'),
    ]

    operations = [
    ]
