# Generated by Django 2.0.6 on 2018-07-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_merge_20180705_1747'),
        ('app', '0019_reportedcamera'),
    ]

    operations = [
    ]
