# Generated by Django 2.0.5 on 2018-07-05 18:59

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_merge_20180705_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='collabimg',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[app.validators.validateURL], verbose_name='Collaborator Logo'),
        ),
    ]
