# Generated by Django 2.0.6 on 2018-07-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_20180707_1439'),
        ('app', '0021_collab_collabimg'),
    ]

    operations = [
    ]
