# Generated by Django 2.0.5 on 2018-07-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_merge_20180707_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcamera',
            name='reporttime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
