# Generated by Django 2.0.5 on 2018-07-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_reportedcamera_reporttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcamera',
            name='reporttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
