# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:11
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180709_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logolink',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[app.validators.validateURL], verbose_name=b'Link to Logo'),
        ),
    ]
