# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sponsor_logolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideheader', models.CharField(blank=True, max_length=100, verbose_name=b'Slide Header')),
                ('slidedescrb', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Slide Description')),
                ('slidelink', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Image Link')),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponname',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'Sponsor'),
        ),
    ]
