# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 16:12
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sponsor_logolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1', models.CharField(max_length=300, validators=[app.validators.validateURL], verbose_name=b'First Slide')),
                ('slide2', models.CharField(max_length=300, validators=[app.validators.validateURL], verbose_name=b'Second Slide')),
                ('slide3', models.CharField(max_length=300, validators=[app.validators.validateURL], verbose_name=b'Third Slide')),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponname',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'Sponsor'),
        ),
    ]
