# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20180711_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='slide2',
        ),
        migrations.RemoveField(
            model_name='index',
            name='slide3',
        ),
    ]
