# Generated by Django 2.0.7 on 2018-07-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180712_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='slideheader',
            field=models.CharField(blank=True, max_length=500, verbose_name='Slide Header'),
        ),
    ]
