# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180711_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='slide',
            new_name='slidelink',
        ),
    ]
