# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20180711_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='slidelink',
            new_name='slide1link',
        ),
    ]
