# Generated by Django 2.0.7 on 2018-07-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20180712_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
