# Generated by Django 2.0.7 on 2018-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideheader', models.CharField(blank=True, max_length=500, verbose_name='SlideHeader')),
                ('slidedescrb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slide Description')),
                ('slidelink', models.CharField(blank=True, max_length=100, null=True, verbose_name='Image Link')),
            ],
        ),
    ]
