# Generated by Django 2.0.7 on 2018-07-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slidenum',
            field=models.IntegerField(null=True, verbose_name='Slide Number'),
        ),
    ]
