# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 19:41
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_index_slide2link'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='slide3link',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, validators=[app.validators.validateURL], verbose_name=b'Third Slide'),
            preserve_default=False,
        ),
    ]
