# Generated by Django 2.0.6 on 2018-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_homepage_slidenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='slideheader',
            field=models.CharField(blank=True, max_length=500, verbose_name='Slide Header'),
        ),
    ]
