# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 20:07
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_index_slide3link'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='slide1descrb',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, validators=[app.validators.validateURL], verbose_name=b'First Slide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='slide1head',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, validators=[app.validators.validateURL], verbose_name=b'First Slide'),
            preserve_default=False,
        ),
    ]
