# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180716_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarinfo', models.CharField(max_length=100, verbose_name=b'Calendar Information')),
            ],
        ),
    ]
