# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 20:13
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180711_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='slide2descrb',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name=b'Slide2 description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='slide2head',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name=b'Slide2 header'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='slide1descrb',
            field=models.CharField(max_length=300, verbose_name=b'Slide1 description'),
        ),
        migrations.AlterField(
            model_name='index',
            name='slide1head',
            field=models.CharField(max_length=300, verbose_name=b'Slide1 header'),
        ),
        migrations.AlterField(
            model_name='index',
            name='slide1link',
            field=models.CharField(max_length=300, validators=[app.validators.validateURL], verbose_name=b'Slide1 imagelink'),
        ),
        migrations.AlterField(
            model_name='index',
            name='slide2link',
            field=models.CharField(max_length=300, validators=[app.validators.validateURL], verbose_name=b'Slide2 imagelink'),
        ),
    ]
