# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20180822_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slidedescrb1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Slide Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slidedescrb',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Slide Description'),
        ),
    ]
