# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-11 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20180823_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcamera',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
    ]
