# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-26 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20180823_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(default=1, max_length=1500, verbose_name='Publication Authors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='conference',
            field=models.CharField(default='add conference', max_length=1500, verbose_name='Publication Conference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='paperinfo',
            field=models.CharField(max_length=1500, verbose_name='Publication Details'),
        ),
    ]
