# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20180826_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Publication Authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conference',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Publication Conference'),
        ),
    ]
