# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20180923_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user', models.TextField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
