# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-29 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20180924_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hasdirector',
            field=models.BooleanField(default=0, verbose_name=b'The team he/she is in has director'),
            preserve_default=False,
        ),
    ]
