# Generated by Django 2.0 on 2018-10-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_video'),
        ('app', '0037_reportedcamera_username'),
        ('app', '0037_auto_20180826_2115'),
    ]

    operations = [
    ]
