# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-19 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20181019_0300'),
        ('app', '0037_reportedcamera_username'),
        ('app', '0045_video'),
    ]

    operations = [
    ]
