# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_merge_20181013_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('usage', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usage')),
            ],
        ),
    ]
