# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-13 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_apirequests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiRequests',
            new_name='ApiRequest',
        ),
    ]
