# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-03 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20181103_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
