# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 01:10
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_subteam_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
