# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20181024_1343'),
    ]

    operations = [

    ]
