# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-10 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20181103_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='TeamMember',
        ),
    ]
