# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models.query import ModelIterable


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20190110_2010'),
    ]

    def splitNames(apps, schema_editor):
        Leader = apps.get_model("app", "leader")
        db_alias = schema_editor.connection.alias
        leaders = Leader.objects.using(db_alias).all()
        for leader in leaders:
            first, last = leader.leadername.rsplit(' ', 1)
            leader.leadername = first
            leader.leaderlastname = last
            leader.save()

    def mergeNames(apps, schema_editor):
        Leader = apps.get_model("app", "leader")
        db_alias = schema_editor.connection.alias
        leaders = Leader.objects.using(db_alias).all()
        for leader in leaders:
            leader.leadername = leader.leadername + ' ' + leader.leaderlastname
            leader.save()

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'past event'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['slidenum'], 'verbose_name': 'homepage slide'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'verbose_name': 'faculty member', 'verbose_name_plural': 'faculty'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team image'},
        ),
        migrations.AddField(
            model_name='leader',
            name='leaderlastname',
            field=models.CharField(default=' ', max_length=50, verbose_name="Faculty Member's Last Name"),
            preserve_default=False,
        ),
        migrations.RunPython(splitNames, mergeNames),
        migrations.AlterField(
            model_name='collab',
            name='collabimg',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Collaborator Logo'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='collablink',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Link to Site'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=500, verbose_name='FAQ answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=200, verbose_name='FAQ question'),
        ),
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.TextField(max_length=500, verbose_name='History Details'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slidedescrb1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Slide Subdescription'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leaderimg',
            field=models.URLField(max_length=300, verbose_name="Faculty Member's Image"),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leadername',
            field=models.CharField(max_length=50, verbose_name="Faculty Member's First and Middle Name"),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leaderpagelink',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name="Faculty Member's Page Link"),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leadertitle',
            field=models.TextField(verbose_name="Faculty Member's Title"),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberimg',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Member Image'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='posterimg',
            field=models.URLField(max_length=300, verbose_name='Poster Image'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paperinfo',
            field=models.TextField(max_length=1500, verbose_name='Publication Details'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paperlink',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Publication Paper Link'),
        ),
        migrations.AlterField(
            model_name='reportedcamera',
            name='reporttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Report Time'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logolink',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Link to Logo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponlink',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Link to Site'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamimg',
            field=models.TextField(max_length=300, verbose_name='Team Image'),
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['leaderlastname'], 'verbose_name': 'faculty member', 'verbose_name_plural': 'faculty'},
        ),
        migrations.AlterField(
            model_name='leader',
            name='leadertitle',
            field=models.TextField(blank=True, null=True, verbose_name="Faculty Member's Title"),
        ),
        migrations.RenameModel(
            old_name='Leader',
            new_name='Faculty',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['lastname'], 'verbose_name': 'faculty member', 'verbose_name_plural': 'faculty'},
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='leaderimg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='leaderlastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='leadername',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='leaderpagelink',
            new_name='pagelink',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='leadertitle',
            new_name='title',
        ),
    ]
