# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20181024_1445'),
    ]

    operations = [
    ]
