# Generated by Django 2.0.6 on 2018-11-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20181103_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Subteam'),
        ),
    ]
