# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20181024_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='iscurrentmember',
            field=models.BooleanField(default=True, verbose_name='Is Current Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='subteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subteam'),
        ),
    ]
