# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-25 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20181024_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isdirector',
            field=models.BooleanField(default=False, verbose_name='Is he/she a Director?'),
        ),
    ]
