# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-02 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20181102_1043'),
    ]

