# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_member_id'),
    ]

