# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20181024_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='subteam',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
