# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20181024_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_url', models.URLField()),
                ('iscurrentmember', models.BooleanField(default=True, verbose_name='Is Current Member')),
                ('subteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subteams')),
            ],
        ),
    ]
