# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email Address', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Email List',
                'verbose_name_plural': 'Email List',
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('email_list', models.ManyToManyField(to='email_system.MailList')),
            ],
            options={
                'verbose_name': 'Send Email to User',
                'verbose_name_plural': 'Emails to send',
            },
        ),
    ]
