# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='email_list',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='email_all_users',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MailList',
        ),
    ]
