# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0002_auto_20170605_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
