# Generated by Django 2.0.6 on 2018-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0005_auto_20180522_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinmodel',
            name='anythingElse',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='courses',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Courses Taken'),
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='gradDate',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Graduation Date'),
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='languages',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Programming Languages'),
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='major',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='tools',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Development Tools'),
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='whyCAM2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reason to Join'),
        ),
    ]
