# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0006_auto_20180627_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'contact'},
        ),
        migrations.AlterModelOptions(
            name='joinmodel',
            options={'verbose_name': 'join request'},
        ),
        migrations.AddField(
            model_name='joinmodel',
            name='favoriteTeams',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='4 Favorite Teams'),
        ),
        migrations.AddField(
            model_name='joinmodel',
            name='futureLeader',
            field=models.BooleanField(default=False, verbose_name='Wants to be a Leader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinmodel',
            name='knowledge',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Knowledge in Various Fields'),
        ),
        migrations.AddField(
            model_name='joinmodel',
            name='problem',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Explain Problem'),
        ),
        migrations.AddField(
            model_name='joinmodel',
            name='teamwork',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Expirience in Teamwork'),
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='gradDate',
            field=models.CharField(default='', max_length=1000, verbose_name='Graduation Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='languages',
            field=models.CharField(default='', max_length=1000, verbose_name='Programming Languages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='major',
            field=models.CharField(default='', max_length=1000, verbose_name='Major'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinmodel',
            name='whyCAM2',
            field=models.CharField(default='', max_length=1000, verbose_name='Reason to Join'),
            preserve_default=False,
        ),
    ]
