# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-15 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from datetime import datetime, timedelta
from pytz import timezone


def getDay(month, day, week):
    """Return datetime.date for monthly option expiration given year and
    month
    Adapted from: https://stackoverflow.com/a/47931869
    """
    # Get the year
    eastern = timezone('US/Eastern')

    # Find the first date in the correct week
    now = datetime.now(tz=eastern)
    dayinweek = datetime(now.year, month, week * 7 - 6, 23, 59, tzinfo=eastern)

    # Replace just the day (of month)
    dayinweek += timedelta(days=(day - dayinweek.weekday()) % 7)

    if now > dayinweek:
        dayinweek = dayinweek.replace(year=dayinweek.year+1)
    return dayinweek

def loadDefaultDeadlines(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ApplicationDeadline = apps.get_model("email_system", "ApplicationDeadline")
    ApplicationDeadline.objects.using(db_alias).bulk_create([
        ApplicationDeadline(name='Summer', show=True, date=getDay(4, 6, 3)),
        ApplicationDeadline(name='Fall', show=True, date=getDay(6, 6, 3)),
        ApplicationDeadline(name='Spring', show=True, date=getDay(12, 6, 2))
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0008_join_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='Application Period')),
                ('show', models.BooleanField(verbose_name='Show the Deadline to the User?')),
                ('date', models.DateTimeField(verbose_name='Cutoff Date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='joinmodel',
            options={'verbose_name': 'application'},
        ),
        migrations.RunPython(loadDefaultDeadlines, migrations.RunPython.noop),
        migrations.AddField(
            model_name='joinmodel',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='email_system.ApplicationDeadline', verbose_name='Application Semester'),
            preserve_default=False,
        ),
    ]
